"""add FeedImpression table for lytir data

Revision ID: 017f3ca2a747
Revises: 6eadae65d404
Create Date: 2026-08-21 22:43:55.445761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '017f3ca2a747'
down_revision: Union[str, Sequence[str], None] = '6eadae65d404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_impressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('feed_session_id', sa.String(), nullable=False),
    sa.Column('feed_variant', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('shown_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('dwell_ms', sa.Integer(), nullable=False),
    sa.Column('voted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('opened_comments', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('shared', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reported', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_version', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_feed_impression_user_session_post', 'feed_impressions', ['user_id', 'feed_session_id', 'post_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_feed_impression_user_session_post', table_name='feed_impressions')
    op.drop_table('feed_impressions')
    # ### end Alembic commands ###
