"""add joined_at field to groupChatMembership table

Revision ID: 237eefa188d5
Revises: f3a9c1d4b2e7
Create Date: 2026-06-08 18:14:58.019178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237eefa188d5'
down_revision: Union[str, Sequence[str], None] = 'f3a9c1d4b2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_chat_memberships', sa.Column('joined_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_chat_memberships', 'joined_at')
    # ### end Alembic commands ###
