"""add role and ban columns to users

Revision ID: 2d158322c3be
Revises: 33b7113910db
Create Date: 2026-10-03 16:34:15.289571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d158322c3be'
down_revision: Union[str, Sequence[str], None] = '33b7113910db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('user', 'moderator', 'admin', name='user_roles').create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', sa.Enum('user', 'moderator', 'admin', name='user_roles'), server_default='user', nullable=False))
    op.add_column('users', sa.Column('banned_until', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('ban_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ban_reason')
    op.drop_column('users', 'banned_until')
    op.drop_column('users', 'role')
    sa.Enum(name="user_roles").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
