"""add key_backups table

Revision ID: 33b7113910db
Revises: 017f3ca2a747
Create Date: 2026-09-25 22:03:37.496090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b7113910db'
down_revision: Union[str, Sequence[str], None] = '017f3ca2a747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_backups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret_type', sa.String(), nullable=False),
    sa.Column('salt', sa.String(), nullable=False),
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('ciphertext', sa.String(), nullable=False),
    sa.Column('opslimit', sa.Integer(), nullable=False),
    sa.Column('memlimit', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("secret_type IN ('login_password', 'custom')", name='ck_key_backups_secret_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key_backups')
    # ### end Alembic commands ###
