"""modify report table

Revision ID: 38ef72cbf703
Revises: a3f8c2e6d9b1
Create Date: 2026-07-03 10:22:41.033624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ef72cbf703'
down_revision: Union[str, Sequence[str], None] = 'a3f8c2e6d9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('story_id', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False))
    op.create_foreign_key('reports_post_id_fkey', 'reports', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('reports_story_id_fkey', 'reports', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reports_story_id_fkey', 'reports', type_='foreignkey')
    op.drop_constraint('reports_post_id_fkey', 'reports', type_='foreignkey')
    op.drop_column('reports', 'status')
    op.drop_column('reports', 'story_id')
    op.drop_column('reports', 'post_id')
    # ### end Alembic commands ###
