"""add tables for E2EE cryptography

Revision ID: 49e7da28fb67
Revises: 6b518be80bb7
Create Date: 2026-06-15 17:57:17.879128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e7da28fb67'
down_revision: Union[str, Sequence[str], None] = '6b518be80bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_keys',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_keys')
    # ### end Alembic commands ###
