"""add group information table

Revision ID: 4c3821012d25
Revises: a50d72088bbd
Create Date: 2026-05-27 15:42:07.606762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3821012d25'
down_revision: Union[str, Sequence[str], None] = 'a50d72088bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_chats', sa.Column('group_name', sa.String(), nullable=True))
    op.add_column('group_chats', sa.Column('profile_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_chats', 'profile_picture')
    op.drop_column('group_chats', 'group_name')
    # ### end Alembic commands ###
