"""add favorite_snack,animal,weekend

Revision ID: 534e11989c36
Revises: c6f5e7dea003
Create Date: 2026-04-22 16:20:59.699097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534e11989c36'
down_revision: Union[str, Sequence[str], None] = 'c6f5e7dea003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('biography', sa.String(), nullable=True))
    op.add_column('users', sa.Column('favorite_animal', sa.String(), nullable=True))
    op.add_column('users', sa.Column('favorite_snack', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ideal_weekend', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ideal_weekend')
    op.drop_column('users', 'favorite_snack')
    op.drop_column('users', 'favorite_animal')
    op.drop_column('users', 'biography')
    # ### end Alembic commands ###
