"""add locations table and location fk

Revision ID: 543e13eec0b3
Revises: f1759e550b1e
Create Date: 2026-07-12 14:50:40.843465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543e13eec0b3'
down_revision: Union[str, Sequence[str], None] = 'f1759e550b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('posts', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key('posts_location_id_fkey', 'posts', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key('users_location_id_fkey', 'users', 'locations', ['location_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_location_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'location_id')
    op.drop_constraint('posts_location_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'location_id')
    op.drop_table('locations')
    # ### end Alembic commands ###
