"""add uuid to message tables

Revision ID: 6b518be80bb7
Revises: b7d2e9f4a1c8
Create Date: 2026-06-12 13:46:31.689907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b518be80bb7'
down_revision: Union[str, Sequence[str], None] = 'b7d2e9f4a1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_message', sa.Column('client_msg_id', sa.String(), nullable=True))
    op.add_column('message', sa.Column('client_msg_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'client_msg_id')
    op.drop_column('group_message', 'client_msg_id')
    # ### end Alembic commands ###
