"""add vote_count to Post table

Revision ID: 6eadae65d404
Revises: c0f3f421137a
Create Date: 2026-07-31 08:26:38.083536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eadae65d404'
down_revision: Union[str, Sequence[str], None] = 'c0f3f421137a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('vote_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###

    # Backfill: bestehende Posts bekommen ihren echten Count aus der votes-Tabelle.
    # count(*) einer korrelierten Subquery ohne Treffer liefert 0 (nicht NULL),
    # daher kein COALESCE noetig. Laeuft einmalig, danach fuehrt vote.py den Zaehler fort.
    op.execute(
        """
        UPDATE posts
        SET vote_count = (
            SELECT count(*)
            FROM votes
            WHERE votes.post_id = posts.id
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'vote_count')
    # ### end Alembic commands ###
