"""add vibe_details to users_table

Revision ID: 9d26b23a7847
Revises: 9a17855a1a52
Create Date: 2026-04-15 19:40:30.039284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d26b23a7847'
down_revision: Union[str, Sequence[str], None] = '9a17855a1a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vibe_factor_1', sa.String(), nullable=True))
    op.add_column('users', sa.Column('vibe_factor_2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vibe_factor_2')
    op.drop_column('users', 'vibe_factor_1')
    # ### end Alembic commands ###
