"""prepare database for messenger

Revision ID: a50d72088bbd
Revises: 18f0e22b9a55
Create Date: 2026-05-25 19:52:54.657940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50d72088bbd'
down_revision: Union[str, Sequence[str], None] = '18f0e22b9a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_chats',
    sa.Column('group_chat_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_chat_id')
    )
    op.create_table('group_chat_memberships',
    sa.Column('group_chat_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_chat_id'], ['group_chats.group_chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_chat_id', 'participant_id')
    )
    op.create_table('group_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_chat_id'], ['group_chats.group_chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_message')
    op.drop_table('group_chat_memberships')
    op.drop_table('group_chats')
    # ### end Alembic commands ###
