"""add DailyBonusLog tabel for ranking

Revision ID: a6db79e328da
Revises: c75a21869085
Create Date: 2026-07-10 12:38:45.892434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6db79e328da'
down_revision: Union[str, Sequence[str], None] = 'c75a21869085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_bonus_log',
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('processed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('awarded_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_bonus_log')
    # ### end Alembic commands ###
