"""report categories and resolved columns

Revision ID: ac967253f52b
Revises: 2d158322c3be
Create Date: 2026-10-03 17:26:54.621873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac967253f52b'
down_revision: Union[str, Sequence[str], None] = '2d158322c3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('details', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('resolved_by', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # Name von Hand: mit None koennte downgrade() den Schluessel nicht wiederfinden.
    op.create_foreign_key('fk_reports_resolved_by_users', 'reports', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Von Hand: autogenerate erkennt CHECK-Constraints nicht.
    # Alte Freitext-Gruende -> 'other', der Text wandert nach details (Tabelle war
    # beim Schreiben leer, das ist nur die Absicherung, damit der CHECK nie scheitert).
    op.execute("""
        UPDATE reports SET details = reason, reason = 'other'
        WHERE reason NOT IN ('spam', 'harassment', 'inappropriate', 'misinformation', 'other')
    """)
    op.create_check_constraint(
        'ck_reports_reason', 'reports',
        "reason IN ('spam', 'harassment', 'inappropriate', 'misinformation', 'other')"
    )
    op.create_check_constraint(
        'ck_reports_status', 'reports',
        "status IN ('pending', 'dismissed', 'action_taken')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_reports_status', 'reports', type_='check')
    op.drop_constraint('ck_reports_reason', 'reports', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_reports_resolved_by_users', 'reports', type_='foreignkey')
    op.drop_column('reports', 'resolved_at')
    op.drop_column('reports', 'resolved_by')
    op.drop_column('reports', 'details')
    # ### end Alembic commands ###
