"""add removed_content

Revision ID: b654da37802f
Revises: a491945c9e59
Create Date: 2026-10-08 20:54:43.164206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b654da37802f'
down_revision: Union[str, Sequence[str], None] = 'a491945c9e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('removed_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('moderation_action_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('removed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_type IN ('post', 'comment', 'story', 'profile_picture')", name='ck_removed_content_target_type'),
    sa.ForeignKeyConstraint(['moderation_action_id'], ['moderation_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('moderation_action_id')
    )
    op.create_index(op.f('ix_removed_content_owner_id'), 'removed_content', ['owner_id'], unique=False)
    op.create_index(op.f('ix_removed_content_removed_at'), 'removed_content', ['removed_at'], unique=False)
    # ### end Alembic commands ###

    # Von Hand: autogenerate sieht CHECK-Aenderungen nicht. Postgres kann einen CHECK nicht
    # aendern, also weg und neu mit 'restore_content'.
    op.drop_constraint('ck_moderation_actions_action', 'moderation_actions', type_='check')
    op.create_check_constraint(
        'ck_moderation_actions_action', 'moderation_actions',
        "action IN ('ban', 'unban', 'resolve_reports', 'delete_post', 'delete_comment', "
        "'delete_story', 'delete_profile_picture', 'role_change', 'restore_content')")


def downgrade() -> None:
    """Downgrade schema."""
    # Schlaegt fehl, wenn schon 'restore_content'-Zeilen im Log stehen. Gewollt: das Audit-Log
    # wird nicht stillschweigend geloescht, die Zeilen muessten vorher von Hand weg.
    op.drop_constraint('ck_moderation_actions_action', 'moderation_actions', type_='check')
    op.create_check_constraint(
        'ck_moderation_actions_action', 'moderation_actions',
        "action IN ('ban', 'unban', 'resolve_reports', 'delete_post', 'delete_comment', "
        "'delete_story', 'delete_profile_picture', 'role_change')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_removed_content_removed_at'), table_name='removed_content')
    op.drop_index(op.f('ix_removed_content_owner_id'), table_name='removed_content')
    op.drop_table('removed_content')
    # ### end Alembic commands ###
