"""extend user table for ranking

Revision ID: c75a21869085
Revises: 7c4d9e2a1b58
Create Date: 2026-07-09 19:15:58.754253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75a21869085'
down_revision: Union[str, Sequence[str], None] = '7c4d9e2a1b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('xp', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('streak_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('last_swipe_date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_swipe_date')
    op.drop_column('users', 'streak_count')
    op.drop_column('users', 'xp')
    # ### end Alembic commands ###
