"""remove favorit snack, animal ideal weekend

Revision ID: fd74bf64e220
Revises: 2f5c18297fb0
Create Date: 2026-05-03 18:10:43.856547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd74bf64e220'
down_revision: Union[str, Sequence[str], None] = '2f5c18297fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_snack')
    op.drop_column('users', 'favorite_animal')
    op.drop_column('users', 'ideal_weekend')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ideal_weekend', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('favorite_animal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('favorite_snack', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
